# Generated by Django 3.2.7 on 2021-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='type',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
