# Generated by Django 3.2.7 on 2021-09-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookmark', '0003_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
